# Generated by Django 5.1.1 on 2024-09-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='licenses/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('more', models.CharField(max_length=70, verbose_name='more')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='asia_logos/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Asian Country',
                'verbose_name_plural': 'Asian Countries',
                'ordering': ('-created',),
            },
        ),
    ]
