# Generated by Django 5.1.1 on 2024-09-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_news_options_remove_news_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='more',
            new_name='description',
        ),
    ]
