# Generated by Django 5.1.1 on 2024-09-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_news_slug_alter_newstranslation_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstranslation',
            name='description',
            field=models.CharField(max_length=5200, verbose_name='description'),
        ),
    ]
