# Generated by Django 5.0.6 on 2024-09-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tenders_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='tenders/'),
        ),
    ]
