# Generated by Django 5.0.6 on 2024-09-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_tenders_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenders',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tenders',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tenders',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenders',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
