# Generated by Django 5.0.6 on 2024-09-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_tenders_end_time_remove_tenders_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenders',
            old_name='start_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='tenders',
            old_name='end_date',
            new_name='start_time',
        ),
    ]
