# Generated by Django 5.0.6 on 2024-09-19 07:05

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_start_date_tenders_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name='Год')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение')),
                ('financial_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financialdata')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.year')),
            ],
            options={
                'verbose_name': 'Данные по году',
                'verbose_name_plural': 'Данные по годам',
            },
        ),
        migrations.AddField(
            model_name='financialdata',
            name='values',
            field=models.ManyToManyField(through='app.FinancialYearData', to='app.year'),
        ),
        migrations.CreateModel(
            name='FinancialDataTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('indicator_name', models.CharField(max_length=255, verbose_name='Показатель')),
                ('unit', models.CharField(max_length=50, verbose_name='Ед. изм.')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.financialdata')),
            ],
            options={
                'verbose_name': 'financial data Translation',
                'db_table': 'app_financialdata_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
