# Generated by Django 5.0.6 on 2024-09-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_financialdata_year_financialyeardata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdata',
            name='values',
        ),
    ]
