# Generated by Django 5.0.6 on 2024-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_financialyeardata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='values',
            field=models.ManyToManyField(blank=True, through='app.FinancialYearData', to='app.year'),
        ),
        migrations.AddField(
            model_name='financialyeardata',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Значение'),
        ),
    ]
