# Generated by Django 5.0.6 on 2024-09-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_financialdata_values_financialyeardata_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdata',
            name='values',
        ),
    ]
