# Generated by Django 5.0.6 on 2024-09-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_financialdata_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyeardata',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение'),
        ),
    ]
