# Generated by Django 5.0.6 on 2024-09-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_financialdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год'),
        ),
    ]
