# Generated by Django 5.0.6 on 2024-09-22 11:55

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Management',
                'verbose_name_plural': 'Managements',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ManagementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('f_i_o', models.CharField(max_length=1500, verbose_name='F_I_O')),
                ('position', models.CharField(max_length=1500, verbose_name='position')),
                ('еducation', models.CharField(max_length=1400, verbose_name='еducation')),
                ('specialization', models.CharField(max_length=1500, verbose_name='specialization')),
                ('phone', models.CharField(max_length=1500, verbose_name='phone')),
                ('admission_date', models.CharField(max_length=1300, verbose_name='admission_date')),
                ('admission_time', models.CharField(max_length=1300, verbose_name='admission_time')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.management')),
            ],
            options={
                'verbose_name': 'Management Translation',
                'db_table': 'app_management_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
