# Generated by Django 5.0.6 on 2024-09-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_management_managementtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='management/'),
        ),
    ]
