# Generated by Django 5.0.6 on 2024-09-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_management_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementtranslation',
            name='birth_date',
            field=models.CharField(default='default-slug', max_length=1500, verbose_name='birth_date'),
            preserve_default=False,
        ),
    ]
