# Generated by Django 5.0.6 on 2024-09-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_managementtranslation_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementtranslation',
            name='birth_date',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='birth_date'),
        ),
    ]
