# Generated by Django 5.0.6 on 2024-09-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_managementtranslation_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementtranslation',
            name='birth_date',
        ),
    ]
