# Generated by Django 5.0.6 on 2024-09-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_departmen_departmentranslation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departmen',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='DepartmenTranslation',
            new_name='DepartmentTranslation',
        ),
        migrations.AlterModelOptions(
            name='departmenttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'department Translation'},
        ),
        migrations.AlterModelTable(
            name='departmenttranslation',
            table='app_department_translation',
        ),
    ]
