# Generated by Django 5.0.6 on 2024-09-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_departmen_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttranslation',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='descriptions'),
        ),
    ]
