# Generated by Django 5.0.6 on 2024-09-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_department_slug_departmenttranslation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenttranslation',
            name='slug',
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
