# Generated by Django 5.0.6 on 2024-09-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_departmenttranslation_slug_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
